### PR TITLE
Renaming 'App' contract to 'AragonApp'

### LINKED ISSUE #173: Rename 'App' contract to 'AragonApp'
It will make easier to identify what app means when Aragon apps are developed outside the Aragon org.

### PR DESCRIPTION
**Pull request by drexpp**
Closes #173

### CODE REVIEW

**Comment by onbjerg** [comment]
The tests are failing because you forgot to change it in the tests as well

**Comment by drexpp** [comment]
Okay, I gonna try to fix the tests as well. Sorry.

**Comment by izqui** [comment]
Awesome, thanks for this!

**Comment by onbjerg** [comment]
@izqui Just noting here that the next published version on npm should be at least 2.0.0 since this breaks every app 😊

**Comment by izqui** [comment]
Current version is 2.0.1, next is 3.0.0 :)

**Comment by onbjerg** [comment]
Oh, sorry! 😅

**Pull request merged**
