### PR TITLE
Docker for contributers

### PR DESCRIPTION
**Pull request by readevalprint**
This can make it easier to get a development environment with Docker.

### CODE REVIEW

**Comment by onbjerg** [comment]
[Solium](https://github.com/duaraghav8/Solium) could be used as the linter

**Comment by izqui** [comment]
Can't get it to run

```
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.0
npm info lifecycle aragon-core@1.0.0~pretest: aragon-core@1.0.0
npm info lifecycle aragon-core@1.0.0~test: aragon-core@1.0.0

> aragon-core@1.0.0 test /usr/src/app
> truffle test

Error: /usr/src/app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
npm info lifecycle aragon-core@1.0.0~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
```

**Comment by izqui** [comment]
We should work on the linter in another PR @onbjerg. I agree it is a good idea to have a linter :)

**Comment by izqui** [comment]
Also should we change TravisCI to just use this?

**Comment by readevalprint** [comment]
@izqui yeah, it would be nice for travis to use this, I'll update .travis.yaml. Can you try deleting `node_modules`. I have a feeling this is going to be a common issue.

**Comment by izqui** [comment]
@readevalprint That worked, lets add `node_modules` to the `.dockerignore`. Also why do you need to manually npm install truffle and truffle@beta. 

Another thing, running this has created 3 directories: `docker_home`, 'test_1176...' and 'tmp-17...' we should add those to the `.gitignore`

**Comment by readevalprint** [comment]
@izqui added to `.dockerignore` and `.gitignore`, as for the `truffle@beta1` it was in `setup.sh` and I just copied it...

**Comment by izqui** [comment]
That was legacy. `npm install` should be enough now

**Pull request merged**
