### PR TITLE
Fix all linting errors

### PR DESCRIPTION
**Pull request by DeveloppSoft**
Just spent some time to fix the remaining errors while running `npm run lint`, I also added the linting tests to the `entrypoint.sh` so it is runned on travis (and in docker).

### CODE REVIEW

**Comment by DeveloppSoft** [comment]
Tests are passing on my laptop, not on travis strange...

**Comment by rudygodoy** [comment]
@DeveloppSoft are you using the same Docker image locally? I have the impression that warnings also return exit code 1, failing the lint step. 

When doing PR #104 I've noticed that solium returns 35 errors, plus 73 warnings. My local setup uses Node 8, and npm 5.3. Docker image uses Node 6 and old npm.

**Comment by izqui** [comment]
Thanks for the contribution! Will fix the remaining error myself :)

**Comment by DeveloppSoft** [comment]
@rudygodoy sorry for the lack of replies, I runned it locally.

**Pull request merged**
